Repository rigetti/pyquil, pull requests merged in 2019-09, with the labels that each got.

#987 Run the GitLab CI test suite on Python 3.7 as well
  .gitlab-ci.yml
  CHANGELOG.md
Labels: devops :rocket:

#991 Delete long-deprecated parameters.py and qpu.py modules
  CHANGELOG.md
  docs/source/basics.rst
  pyquil/_parser/PyQuilListener.py
  pyquil/device.py
  pyquil/noise.py
  pyquil/parameters.py
  pyquil/qpu.py
  pyquil/quil.py
  pyquil/quilbase.py
  pyquil/tests/test_parameters.py
  pyquil/tests/test_parser.py
  pyquil/tests/test_quil.py
Labels: quality :art:

#992 Set --use-seed default to True to make UTs much faster
  CHANGELOG.md
  DEVELOPMENT.md
  pyquil/tests/conftest.py
Labels: devops :rocket:

#975 Allow non-gate instructions in to_latex()
  CHANGELOG.md
  pyquil/latex/latex_generation.py
Labels: bug :bug:

#998 Reduce deprecated feature warnings in tests
  CHANGELOG.md
  pyquil/api/_qvm.py
  pyquil/operator_estimation.py
  pyquil/tests/test_api.py
  pyquil/tests/test_magic.py
  pyquil/tests/test_numpy_simulator.py
  pyquil/tests/test_operator_estimation.py
  pyquil/tests/test_quantum_computer.py
  pyquil/tests/test_quil.py
  pyquil/tests/test_reference_wavefunction_simulator.py
  pyquil/tests/test_unitary_tools.py
Labels: quality :art:

#1001 Mark and skip particularly slow unit tests
  CHANGELOG.md
  CONTRIBUTING.md
  pyquil/tests/conftest.py
  pyquil/tests/test_operator_estimation.py
  pyquil/tests/test_quantum_computer.py
  pyquil/tests/test_reference_density_simulator.py
  tox.ini
Labels: devops :rocket:

#1005 Clean up bulk of remaining test suite warnings
  CHANGELOG.md
  pyquil/paulis.py
  pyquil/tests/test_api.py
  pyquil/tests/test_device.py
  pyquil/tests/test_parser.py
  pyquil/tests/test_paulis.py
  pyquil/tests/test_paulis_with_placeholders.py
  pyquil/tests/test_quantum_computer.py
  pyquil/tests/test_quil.py
  pyquil/tests/test_qvm.py
Labels: devops :rocket:, quality :art:

#1010 Fix operand types for STORE and comparison instructions
  CHANGELOG.md
  pyquil/gates.py
  pyquil/quilbase.py
  pyquil/tests/test_parser.py
  pyquil/tests/test_quil.py
Labels: bug :bug:

#1012 Prevent non-constant params in lifted_gate
  CHANGELOG.md
  pyquil/tests/test_unitary_tools.py
  pyquil/unitary_tools.py
Labels: bug :bug:
