Repository rigetti/pyquil, pull requests merged in 2019-11, with the labels that each got.

#1074 Overhaul Quil to LaTeX circuit generation
  CHANGELOG.md
  NOTICE.md
  docs/source/apidocs/visualization.rst
  docs/source/index.rst
  examples/LaTeXQuilCircuits.ipynb
  pyquil/latex/__init__.py
  pyquil/latex/_diagram.py
  pyquil/latex/_ipython.py
  pyquil/latex/latex_config.py
  pyquil/latex/latex_generation.py
  pyquil/latex/tests/__init__.py
  pyquil/latex/tests/test_latex.py
  pyquil/tests/test_latex.py
  requirements.txt
  setup.py
Labels: enhancement :sparkles:

#1093 Support Python 3.8 and include in the CI suite
  .gitlab-ci.yml
  pyquil/magic.py
  setup.py
Labels: devops :rocket:

#1094 Move the new module __init__.py code elsewhere
  CHANGELOG.md
  pyquil/device/__init__.py
  pyquil/device/_main.py
  pyquil/experiment/__init__.py
  pyquil/experiment/_main.py
  pyquil/experiment/tests/test_experiment.py
  pyquil/latex/__init__.py
  pyquil/latex/_diagram.py
  pyquil/latex/_ipython.py
  pyquil/latex/_main.py
  pyquil/latex/latex_generation.py
Labels: refactor :hammer:

#1075 Add type annotations to the PauliTerm class
  CHANGELOG.md
  pyquil/paulis.py
Labels: quality :art:

#1105 Redirect qvm/quilc output in the Docker image entrypoint
  CHANGELOG.md
  entrypoint.sh
Labels: devops :rocket:

#1098 Add "make typecheck" target and run it during gitlab CI
  .gitlab-ci.yml
  CHANGELOG.md
  Makefile
  mypy.ini
  requirements.txt
  tox.ini
Labels: devops :rocket:

#1103 Fix control line offset in LaTeX for controlled gates
  CHANGELOG.md
  pyquil/latex/_diagram.py
  pyquil/latex/tests/test_latex.py
Labels: bug :bug:

#1107 Bump QVM docker image version to v1.13.1 for XY
  Dockerfile
Labels: devops :rocket:

#1099 Correctly declare the size of the ro register in qc.run example
  CHANGELOG.md
  docs/source/qvm.rst
Labels: documentation :memo:

#1102 Specify file encoding to guard against ascii locales
  CHANGELOG.md
  pyquil/experiment/_main.py
  setup.py
Labels: bug :bug:

#1111 Add missing XY values when generating specs from graph
  CHANGELOG.md
  pyquil/device/_specs.py
Labels: bug :bug:

#1108 Remove tox.ini and readthedocs.yml, add .flake8
  .flake8
  CHANGELOG.md
  readthedocs.yml
  requirements.txt
  tox.ini
Labels: quality :art:

#1104 Add type annotations to the PauliSum class
  CHANGELOG.md
  pyquil/paulis.py
Labels: quality :art:

#1100 QuantumComputer method to run TomographyExperiments
  CHANGELOG.md
  docs/source/apidocs/experiment.rst
  docs/source/apidocs/operator_estimation.rst
  docs/source/apidocs/quantum_computer.rst
  docs/source/index.rst
  pyquil/api/_qam.py
  pyquil/api/_quantum_computer.py
  pyquil/api/tests/__init__.py
  pyquil/api/tests/test_quantum_computer.py
  pyquil/experiment/__init__.py
  pyquil/experiment/_main.py
  pyquil/experiment/_memory.py
  pyquil/experiment/_program.py
  pyquil/experiment/_result.py
  pyquil/experiment/_setting.py
  pyquil/experiment/_symmetrization.py
  pyquil/experiment/tests/test_experiment.py
  pyquil/experiment/tests/test_main.py
  pyquil/experiment/tests/test_memory.py
  pyquil/experiment/tests/test_program.py
  pyquil/experiment/tests/test_result.py
  pyquil/experiment/tests/test_setting.py
Labels: enhancement :sparkles:
