Repository rigetti/pyquil, pull requests merged in 2019-12, with the labels that each got.

#1113 Run flake8 on the docs and examples directories as well
  CHANGELOG.md
  Makefile
  docs/source/conf.py
  examples/1.3_vqe_demo.py
  examples/quantum_die.py
Labels: quality :art:

#1125 Add support for DEFGATE ... AS PAULI-SUM
  CHANGELOG.md
  pyquil/_parser/PyQuilListener.py
  pyquil/_parser/Quil.g4
  pyquil/_parser/gen3/Quil.tokens
  pyquil/_parser/gen3/QuilLexer.py
  pyquil/_parser/gen3/QuilLexer.tokens
  pyquil/_parser/gen3/QuilListener.py
  pyquil/_parser/gen3/QuilParser.py
  pyquil/paulis.py
  pyquil/pyqvm.py
  pyquil/quilatom.py
  pyquil/quilbase.py
  pyquil/tests/test_paulis.py
  pyquil/tests/test_quil.py
Labels: enhancement :sparkles:

#1116 Minor fixes for VQE demo and quantum walk examples
  CHANGELOG.md
  examples/1.3_vqe_demo.py
  examples/quantum_walk.ipynb
  examples/requirements.txt
Labels: bug :bug:

#1120 Add unit test for validating trotterization order
  CHANGELOG.md
  pyquil/paulis.py
  pyquil/tests/test_paulis.py
Labels: enhancement :sparkles:

#1123 Re-engineer QPU engagement and authorization
  .gitignore
  CHANGELOG.md
  docs/source/advanced_usage.rst
  pyquil/api/_base_connection.py
  pyquil/api/_benchmark.py
  pyquil/api/_compiler.py
  pyquil/api/_config.py
  pyquil/api/_devices.py
  pyquil/api/_errors.py
  pyquil/api/_logger.py
  pyquil/api/_qpu.py
  pyquil/api/_quantum_computer.py
  pyquil/api/tests/data/forest_config.ini
  pyquil/api/tests/data/qcs_config.ini
  pyquil/api/tests/data/qmi_auth_token_invalid.json
  pyquil/api/tests/data/qmi_auth_token_valid.json
  pyquil/api/tests/data/user_auth_token_invalid.json
  pyquil/api/tests/data/user_auth_token_valid.json
  pyquil/api/tests/test_base_connection.py
  pyquil/api/tests/test_config.py
  pyquil/tests/test_qpu.py
  pyquil/tests/utils.py
  requirements.txt
  setup.py
Labels: enhancement :sparkles:

#1127 Add support for QPU compilation over http(s)
  CHANGELOG.md
  pyquil/api/_compiler.py
  pyquil/api/tests/test_compiler.py
Labels: enhancement :sparkles:

#1128 Bump quilc / qvm parent Docker images to v1.15.1
  CHANGELOG.md
  Dockerfile
Labels: devops :rocket:

#1130 Only request engagement from dispatch when necessary
  CHANGELOG.md
  pyquil/api/_config.py
  pyquil/api/_qpu.py
  pyquil/api/tests/test_config.py
  pyquil/tests/test_qpu.py
Labels: bug :bug:

#1129 Bump version to 2.15.0
  .dockerignore
  CHANGELOG.md
  VERSION.txt
Labels: devops :rocket:

#1122 Send local_forest_runtime stdout and stderr to DEVNULL
  CHANGELOG.md
  pyquil/api/_quantum_computer.py
Labels: bug :bug:

#1115 Partially add type annotations to the Program class
  CHANGELOG.md
  pyquil/quil.py
Labels: quality :art:

#1133 Ignore fewer flake8 rules, add flake8-bugbear
  .flake8
  .gitlab-ci.yml
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  examples/1.3_vqe_demo.py
  examples/qaoa_ansatz.py
  examples/website-script.py
  pyproject.toml
  pyquil/api/_base_connection.py
  pyquil/api/_compiler.py
  pyquil/api/_qpu.py
  pyquil/api/_quantum_computer.py
  pyquil/api/_qvm.py
  pyquil/api/tests/test_config.py
  pyquil/experiment/_memory.py
  pyquil/experiment/_setting.py
  pyquil/gates.py
  pyquil/latex/_diagram.py
  pyquil/latex/tests/test_latex.py
  pyquil/noise.py
  pyquil/numpy_simulator.py
  pyquil/pyqvm.py
  pyquil/quil.py
  pyquil/quilatom.py
  pyquil/tests/test_gate_matrices.py
  pyquil/tests/test_magic.py
  pyquil/tests/test_noise.py
  pyquil/tests/test_numpy_simulator.py
  pyquil/tests/test_operator_estimation.py
  pyquil/tests/test_parameters.py
  pyquil/tests/test_parser.py
  pyquil/tests/test_paulis.py
  pyquil/tests/test_paulis_with_placeholders.py
  pyquil/tests/test_qpu.py
  pyquil/tests/test_quantum_computer.py
  pyquil/tests/test_quil.py
  pyquil/tests/test_qvm.py
  pyquil/tests/test_reference_density_simulator.py
  pyquil/tests/test_reference_wavefunction_simulator.py
  pyquil/tests/test_unitary_tools.py
  requirements.txt
Labels: devops :rocket:, quality :art:

#1136 Add type annotations to noise.py and verify in the CI
  CHANGELOG.md
  Makefile
  docs/source/apidocs/noise.rst
  pyquil/noise.py
  pyquil/quil.py
Labels: quality :art:

#1139 Fix string concatenation style
  CHANGELOG.md
  pyquil/gates.py
  pyquil/quilbase.py
Labels: quality :art:

#1138 Fixes for migration2-qc.ipynb
  CHANGELOG.md
  docs/source/migration2-qc.ipynb
  pyquil/api/_quantum_computer.py
Labels: bug :bug:

#1137 Remove unused method Program._out() in quil.py
  CHANGELOG.md
  pyquil/quil.py
Labels: quality :art:

#1141 Ensure valid RST in docstrings
  CHANGELOG.md
  pyquil/api/_base_connection.py
  pyquil/api/_config.py
  pyquil/api/_devices.py
  pyquil/api/_qpu.py
  pyquil/api/_quantum_computer.py
  pyquil/experiment/_main.py
  pyquil/experiment/_program.py
  pyquil/magic.py
  pyquil/noise.py
  pyquil/numpy_simulator.py
  pyquil/pyqvm.py
  pyquil/reference_simulator.py
Labels: quality :art:

#1134 Finish the rest of the type annotations for quil.py
  CHANGELOG.md
  Makefile
  pyquil/noise.py
  pyquil/quil.py
Labels: quality :art:

#1078 Add helper to separate ExperimentResults
  CHANGELOG.md
  pyquil/experiment/_group.py
  pyquil/experiment/tests/test_group.py
  pyquil/operator_estimation.py
Labels: enhancement :sparkles:

#1142 Add typing to the latex module and mypy check in CI
  CHANGELOG.md
  Makefile
  mypy.ini
  pyquil/latex/_diagram.py
  pyquil/latex/_ipython.py
  pyquil/latex/_main.py
  pyquil/latex/latex_generation.py
Labels: devops :rocket:, quality :art:

#1077 Add helper to merge TomographyExperiments
  CHANGELOG.md
  pyquil/experiment/__init__.py
  pyquil/experiment/_group.py
  pyquil/experiment/tests/test_group.py
  pyquil/operator_estimation.py
  pyquil/tests/test_operator_estimation.py
Labels: enhancement :sparkles:

#1143 Move Python-based simulation tools to a subdirectory
  CHANGELOG.md
  Makefile
  examples/1.3_vqe_demo.py
  pyquil/gate_matrices.py
  pyquil/numpy_simulator.py
  pyquil/pyqvm.py
  pyquil/reference_simulator.py
  pyquil/simulation/__init__.py
  pyquil/simulation/_numpy.py
  pyquil/simulation/_reference.py
  pyquil/simulation/matrices.py
  pyquil/simulation/tests/__init__.py
  pyquil/simulation/tests/test_matrices.py
  pyquil/simulation/tests/test_numpy.py
  pyquil/simulation/tests/test_reference_density.py
  pyquil/simulation/tests/test_reference_wavefunction.py
  pyquil/simulation/tests/test_tools.py
  pyquil/simulation/tools.py
  pyquil/tests/test_paulis.py
  pyquil/unitary_tools.py
Labels: devops :rocket:, quality :art:

#1145 Start using Travis CI, upgrade style checks to py37
  .github/PULL_REQUEST_TEMPLATE.md
  .gitlab-ci.yml
  .travis.yml
  CHANGELOG.md
  pyquil/latex/_diagram.py
Labels: devops :rocket:
