Repository rigetti/pyquil, pull requests merged in 2019-10, with the labels that each got.

#1032 Add a Makefile containing common build operations
  .gitlab-ci.yml
  CHANGELOG.md
  Makefile
  requirements.txt
Labels: devops :rocket:

#1035 Add Dockerfile containing pyQuil and the Forest SDK
  .gitlab-ci.yml
  CHANGELOG.md
  CONTRIBUTING.md
  Dockerfile
  Makefile
  entrypoint.sh
Labels: devops :rocket:

#1045 Correct path to exercises.rst in meyer_penny_game.py
  CHANGELOG.md
  examples/meyer_penny_game.py
Labels: bug :bug:

#1039 Make the Docker image smaller and build faster
  .dockerignore
  .gitlab-ci.yml
  CHANGELOG.md
  Dockerfile
Labels: devops :rocket:

#1042 Update Rigetti Forest Slack Workspace invitation link
  CHANGELOG.md
  README.md
Labels: bug :bug:

#1038 Package and push to TestPyPI every commit
  .gitlab-ci.yml
  CHANGELOG.md
  CONTRIBUTING.md
  Dockerfile
  MANIFEST.in
  Makefile
  VERSION.txt
  pyquil/__init__.py
  pyquil/version.py
  setup.py
Labels: devops :rocket:

#1052 Start testing and reporting code coverage in the CI
  .coveragerc
  .gitlab-ci.yml
  CHANGELOG.md
  CONTRIBUTING.md
  Dockerfile
  Makefile
  pyquil/_parser/README.md
  requirements.txt
Labels: devops :rocket:

#1043 Separate program generation from measure_observables.
  CHANGELOG.md
  pyquil/operator_estimation.py
Labels: refactor :hammer:

#1060 Remove all uses of py2-supporting __future__ and six
  CHANGELOG.md
  docs/source/noise.rst
  examples/ReadoutNoise.ipynb
  examples/pointer.py
  examples/quantum_die.py
  examples/run_quil.py
  pyquil/api/_base_connection.py
  pyquil/api/_config.py
  pyquil/api/_qvm.py
  pyquil/api/_wavefunction_simulator.py
  pyquil/noise.py
  pyquil/paulis.py
  pyquil/quil.py
  pyquil/quilatom.py
  pyquil/quilbase.py
  pyquil/tests/test_paulis.py
  pyquil/tests/test_paulis_with_placeholders.py
  pyquil/wavefunction.py
  requirements.txt
  setup.py
Labels: quality :art:

#1064 Move conftest.py to the project's top-level directory
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  conftest.py
Labels: devops :rocket:

#1071 Deprecate positional usage of protoquil compilation arg
  CHANGELOG.md
  docs/source/compiler.rst
  pyquil/api/_qac.py
  pyquil/api/_quantum_computer.py
  pyquil/tests/utils.py
Labels: refactor :hammer:

#1066 Move device-related code into its own subdirectory
  CHANGELOG.md
  pyquil/device.py
  pyquil/device/__init__.py
  pyquil/device/_isa.py
  pyquil/device/_specs.py
  pyquil/device/tests/__init__.py
  pyquil/device/tests/test_device.py
Labels: quality :art:

#1076 Test for presence of π in _expression_to_string
  CHANGELOG.md
  pyquil/quilatom.py
  pyquil/tests/test_quil.py
Labels: bug :bug:

#1073 Add hash function to PauliSum
  CHANGELOG.md
  pyquil/paulis.py
Labels: enhancement :sparkles:

#1080 Add __repr__ magic methods for PauliSum and PauliTerm
  CHANGELOG.md
  pyquil/paulis.py
Labels: enhancement :sparkles:

#1047 Call qc.run_symmetrized_readout in measure_observables
  CHANGELOG.md
  pyquil/operator_estimation.py
  pyquil/tests/test_operator_estimation.py
Labels: refactor :hammer:

#1067 Reinstate support for user-defined gates in PyQVM.execute
  CHANGELOG.md
  pyquil/pyqvm.py
  pyquil/tests/test_numpy_simulator.py
Labels: bug :bug:

#1072 Check if pyquil_config.qpu_url exists during QPU reset
  CHANGELOG.md
  pyquil/api/_qpu.py
Labels: bug :bug:

#1084 Move experiment schema code to a new experiment module
  CHANGELOG.md
  pyquil/experiment/__init__.py
  pyquil/experiment/_result.py
  pyquil/experiment/_setting.py
  pyquil/experiment/tests/__init__.py
  pyquil/experiment/tests/test_experiment.py
  pyquil/operator_estimation.py
  pyquil/tests/test_operator_estimation.py
  pyquil/tests/test_reference_density_simulator.py
  pyquil/tests/test_unitary_tools.py
  pyquil/unitary_tools.py
Labels: refactor :hammer:

#999 Type annotations for gates, quilatom, and quilbase modules
  CHANGELOG.md
  pyquil/_parser/PyQuilListener.py
  pyquil/api/_base_connection.py
  pyquil/api/_quantum_computer.py
  pyquil/api/_qvm.py
  pyquil/gates.py
  pyquil/operator_estimation.py
  pyquil/quilatom.py
  pyquil/quilbase.py
  pyquil/tests/test_gates.py
  pyquil/tests/test_reference_wavefunction_simulator.py
Labels: quality :art:

#1090 Use TomographyExperiment for measure_observables args
  CHANGELOG.md
  pyquil/experiment/__init__.py
  pyquil/experiment/tests/test_experiment.py
  pyquil/operator_estimation.py
  pyquil/tests/test_operator_estimation.py
Labels: enhancement :sparkles:

#1089 Remove unused code for talking to quilc over HTTP
  CHANGELOG.md
  pyquil/api/_base_connection.py
Labels: bug :bug:
