Repository rigetti/pyquil, pull requests merged in 2020-01, with the labels that each got.

#1146 Add typing to experiment module and verify in CI
  CHANGELOG.md
  Makefile
  pyquil/experiment/_group.py
  pyquil/experiment/_main.py
  pyquil/experiment/_program.py
  pyquil/experiment/_result.py
  pyquil/experiment/_setting.py
  pyquil/latex/_ipython.py
Labels: devops :rocket:, quality :art:

#1144 Delete api/_job.py, JobConnection, and SyncConnection
  CHANGELOG.md
  pyquil/api/__init__.py
  pyquil/api/_job.py
Labels: quality :art:

#1149 Use dataclasses instead of namedtuples in device module
  CHANGELOG.md
  Makefile
  pyquil/device/_isa.py
  pyquil/device/_main.py
  pyquil/device/_specs.py
  pyquil/device/tests/test_device.py
  pyquil/tests/test_quantum_computer.py
Labels: refactor :hammer:

#1147 Reduce mypy errors in paulis.py
  CHANGELOG.md
  pyquil/experiment/_group.py
  pyquil/experiment/_main.py
  pyquil/experiment/_memory.py
  pyquil/experiment/_setting.py
  pyquil/paulis.py
  pyquil/simulation/_numpy.py
  pyquil/simulation/_reference.py
Labels: quality :art:

#1151 NxDevices support CZ and XY by default
  CHANGELOG.md
  pyquil/device/_isa.py
  pyquil/device/_main.py
  pyquil/device/tests/test_device.py
Labels: bug :bug:

#1152 QuantumComputer method to perform readout calibration
  CHANGELOG.md
  docs/source/apidocs/experiment.rst
  docs/source/apidocs/quantum_computer.rst
  pyquil/api/_quantum_computer.py
  pyquil/api/tests/test_quantum_computer.py
  pyquil/experiment/__init__.py
  pyquil/experiment/_calibration.py
  pyquil/experiment/_main.py
  pyquil/experiment/_result.py
  pyquil/experiment/_setting.py
  pyquil/experiment/tests/test_main.py
  pyquil/experiment/tests/test_result.py
  pyquil/noise.py
  pyquil/operator_estimation.py
  pyquil/tests/test_operator_estimation.py
Labels: enhancement :sparkles:

#1114 Support instead providing a list of values to write_memory()
  CHANGELOG.md
  pyquil/api/_qam.py
  pyquil/api/_quantum_computer.py
Labels: refactor :hammer:

#1150 Add type hints to all remaining top-level files
  CHANGELOG.md
  Makefile
  mypy.ini
  pyquil/operator_estimation.py
  pyquil/parser.py
  pyquil/paulis.py
  pyquil/pyqvm.py
  pyquil/tests/test_wavefunction.py
  pyquil/wavefunction.py
Labels: devops :rocket:, quality :art:

#1157 Add type annotations to the whole pyquil.api module
  .flake8
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  pyquil/api/__init__.py
  pyquil/api/_base_connection.py
  pyquil/api/_benchmark.py
  pyquil/api/_compiler.py
  pyquil/api/_config.py
  pyquil/api/_devices.py
  pyquil/api/_error_reporting.py
  pyquil/api/_errors.py
  pyquil/api/_qac.py
  pyquil/api/_qam.py
  pyquil/api/_qpu.py
  pyquil/api/_quantum_computer.py
  pyquil/api/_qvm.py
  pyquil/api/_wavefunction_simulator.py
Labels: devops :rocket:, quality :art:

#1158 Rename TomographyExperiment to Experiment
  CHANGELOG.md
  docs/source/apidocs/experiment.rst
  pyquil/api/_qam.py
  pyquil/api/_quantum_computer.py
  pyquil/api/tests/test_quantum_computer.py
  pyquil/experiment/__init__.py
  pyquil/experiment/_group.py
  pyquil/experiment/_main.py
  pyquil/experiment/_setting.py
  pyquil/experiment/tests/test_group.py
  pyquil/experiment/tests/test_main.py
  pyquil/operator_estimation.py
  pyquil/simulation/tests/test_reference_density.py
  pyquil/tests/test_operator_estimation.py
Labels: quality :art:

#1163 Pin antlr4-python3-runtime to under 4.8
  CHANGELOG.md
  mypy.ini
  requirements.txt
  setup.py
Labels: devops :rocket:

#1164 Fix QPUCompiler init args in test_qpu.py
  CHANGELOG.md
  pyquil/tests/test_qpu.py
Labels: bug :bug:

#1160 Actually track metadata in experiment manipulations
  CHANGELOG.md
  pyquil/experiment/_group.py
  pyquil/experiment/_main.py
Labels: bug :bug:

#1165 Expand upon the acknowledgements file
  ACKNOWLEDGEMENTS.md
  CHANGELOG.md
Labels: documentation :memo:

#1166 Use the job template YAMLs from rigetti/gitlab-pipelines
  .gitlab-ci.yml
  CHANGELOG.md
  CONTRIBUTING.md
Labels: devops :rocket:

#1167 Remove examples dir in favor of forest-tutorials repo
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  examples/1.3_vqe_demo.py
  examples/GateNoiseModels.ipynb
  examples/H2_sto-3g_singlet.inp
  examples/LaTeXQuilCircuits.ipynb
  examples/NoiseInvestigation.ipynb
  examples/QubitPlaceholder.ipynb
  examples/README.md
  examples/ReadoutNoise.ipynb
  examples/circuit.png
  examples/forest2-simple-prog.py
  examples/hello_world.quil
  examples/meyer_penny_game.py
  examples/old-website-script.py
  examples/pointer.py
  examples/qaoa_ansatz.py
  examples/quantum_die.py
  examples/quantum_walk.ipynb
  examples/requirements.txt
  examples/run_quil.py
  examples/teleportation.py
  examples/website-script.py
  pyquil/tests/test_examples.py
  setup.py
Labels: documentation :memo:

#1168 Another round of README cleanup and improvements
  .gitlab-ci.yml
  CHANGELOG.md
  Makefile
  README.md
  requirements.txt
Labels: documentation :memo:
